name: reusable-cdk-tests

on:
  workflow_call:
    inputs:
      AUDIT_LEVEL:
        description: "Define npm audit level (empty: doesn't run)"
        type: string

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ vars.INFRA_PATH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # was: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # was: actions/setup-node@v4
        with:
          node-version-file: "${{ vars.INFRA_PATH }}/.nvmrc"
          cache: npm
          cache-dependency-path: "${{ vars.INFRA_PATH }}/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  audit:
    name: audit
    runs-on: ubuntu-latest
    if: ${{ inputs.AUDIT_LEVEL }}
    defaults:
      run:
        working-directory: ${{ vars.INFRA_PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # was: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # was: actions/setup-node@v4
        with:
          node-version-file: "${{ vars.INFRA_PATH }}/.nvmrc"
          cache: npm
          cache-dependency-path: "${{ vars.INFRA_PATH }}/package-lock.json"

      - name: Run audit
        id: audit
        continue-on-error: true # audit is important but it's not blocking the PR / release process
        run: npm audit --audit-level ${{ inputs.AUDIT_LEVEL }} > ${{ vars.AUDIT_SUMMARY_FILE }}

      - name: Audit results into workflow summary
        run: cat ${{ vars.AUDIT_SUMMARY_FILE }}  > $GITHUB_STEP_SUMMARY

      - name: If audit step was not successful or cancelled, enforce error
        if: ${{ steps.audit.outcome != 'success' && steps.audit.outcome != 'cancelled' }}
        run: |
          echo "npm audit failed"
          exit 1
