name: reusable-dispatcher

on:
  workflow_call:
    inputs:
      filters:
        description: "dispatcher paths-filter YAML"
        type: string
        required: true
    outputs:
      changes:
        description: "True if any of the provided filters matches"
        value: ${{ jobs.dispatcher.outputs.changes }}

permissions:
  contents: read

jobs:
  dispatcher:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # was: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # was: dorny/paths-filter@v3
        with:
          filters: ${{ inputs.filters }}
