name: reusable-dispatcher

on:
  workflow_call:
    inputs:
      filters:
        description: "dispatcher paths-filter YAML"
        type: string
        required: true
    outputs:
      changes:
        description: "True if any of the provided filters matches"
        value: ${{ jobs.dispatcher.outputs.changes }}

permissions:
  contents: read

jobs:
  dispatcher:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # was: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get last two tags
        id: code-snapshot
        run: |
          if [ -n "${{ github.event.release.tag_name }}" ]; then
            tags=($(git tag --sort=-creatordate))
            echo "previous=${tags[1]}" >> $GITHUB_OUTPUT
            echo "latest=${tags[0]}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            # compare last commit vs commit before push
            echo "previous=${GITHUB_EVENT_BEFORE}" >> $GITHUB_OUTPUT
            echo "latest=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          else
             # PRs: base is automatically the PR base branch, so leaving it empty
            echo "previous=" >> $GITHUB_OUTPUT
            echo "latest=${GITHUB_REF}" >> $GITHUB_OUTPUT
          fi

      - id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # was: dorny/paths-filter@v3
        with:
          filters: ${{ inputs.filters }}
          base: ${{ steps.code-snapshot.outputs.previous }}
          ref: ${{ steps.code-snapshot.outputs.latest }}
