name: Staging Workflow

on:
  push:
    branches:
      - main
      - feature/add-cdk-infrastructure-stacks # FIXME: Remove

concurrency:
  group: staging-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false # only cancel in-progress runs for PRs

permissions:
  contents: read
  id-token: write
  actions: write

jobs:
  dispatcher:
    uses: ./.github/workflows/reusable-dispatcher.yml
    with:
      filters: |
        changes:
          - 'infrastructure/**'
          - 'web/**'
          - '.github/workflows/**'
          - '!**/*.md'

  # Just run a single test. It internally checks all envs
  cdk_tests:
    if: ${{ needs.dispatcher.outputs.changes == 'true' }}
    needs: dispatcher
    uses: ./.github/workflows/reusable-cdk-tests.yml
    with:
      AUDIT_LEVEL: moderate

  # We can skip the diff, as deploy it's automated (and was reviewed in PR), but I prefer a fail-fast approach if something's wrong
  cdk_diff:
    if: ${{ needs.dispatcher.outputs.changes == 'true' }}
    needs: dispatcher
    uses: ./.github/workflows/reusable-cdk-diff.yml
    with:
      CDK_ENVIRONMENT: stag
      WEB_MAIN_DOMAIN_NAME: staging.adriantunez.cloud
      WEB_DOMAIN_NAMES: staging.adriantunez.cloud,www-staging.adriantunez.cloud
      WEB_SSM_SP_BUCKET_NAME: /web/stag/bucketName
      WEB_SSM_SP_DISTRIBUTION_ID: /web/stag/distributionId
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACM_CERTIFICATE_ID: ${{ secrets.AWS_ACM_CERTIFICATE_ID }}
      AWS_OIDC_ASSUME_ROLE: ${{ secrets.AWS_STAG_DIFF_ROLE_ARN }}

  cdk_deploy:
    if: ${{ needs.dispatcher.outputs.changes == 'true' }}
    needs: [cdk_tests, cdk_diff]
    uses: ./.github/workflows/reusable-cdk-deploy.yml
    with:
      CDK_ENVIRONMENT: stag
      GHA_ENVIRONMENT: stag-infrastructure
      WEB_MAIN_DOMAIN_NAME: staging.adriantunez.cloud
      WEB_DOMAIN_NAMES: staging.adriantunez.cloud,www-staging.adriantunez.cloud
      WEB_SSM_SP_BUCKET_NAME: /web/stag/bucketName
      WEB_SSM_SP_DISTRIBUTION_ID: /web/stag/distributionId
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACM_CERTIFICATE_ID: ${{ secrets.AWS_ACM_CERTIFICATE_ID }}
      AWS_OIDC_ASSUME_ROLE: ${{ secrets.AWS_CDK_DEPLOY_OIDC_ASSUME_ROLE }}

  hugo:
    if: ${{ needs.dispatcher.outputs.changes == 'true' }}
    needs: [cdk_diff, cdk_deploy]
    uses: ./.github/workflows/reusable-hugo.yml
    with:
      GHA_ENVIRONMENT: stag-web
      HUGO_ENVIRONMENT: stag
      HUGO_CONFIGS: config/_default/hugo.toml,config/stag/hugo-override.toml
      WEB_MAIN_DOMAIN_NAME: staging.adriantunez.cloud
      WEB_SSM_SP_BUCKET_NAME: /web/stag/bucketName
      WEB_SSM_SP_DISTRIBUTION_ID: /web/stag/distributionId
    secrets:
      AWS_OIDC_ASSUME_ROLE: ${{ secrets.AWS_WEB_DEPLOY_OIDC_ASSUME_ROLE }}
