name: Staging Workflow

on:
  push:
    branches:
      - main

concurrency:
  group: staging-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false # only cancel in-progress runs for PRs

permissions:
  contents: read
  id-token: write
  actions: write

jobs:
  dispatcher:
    uses: ./.github/workflows/reusable-dispatcher.yml
    with:
      filters: .github/filters.yml

  # Just run a single test. It internally checks all envs
  cdk_tests:
    if: ${{ needs.dispatcher.outputs.changes == 'true' }}
    needs: dispatcher
    uses: ./.github/workflows/reusable-cdk-tests.yml
    with:
      AUDIT_LEVEL: moderate

  cdk_deploy:
    if: ${{ needs.dispatcher.outputs.changes == 'true' }}
    needs: [cdk_tests]
    uses: ./.github/workflows/reusable-cdk-deploy.yml
    with:
      CDK_ENVIRONMENT: stag
      GHA_ENVIRONMENT: stag-infrastructure
      WEB_MAIN_DOMAIN_NAME: ${{ vars.STAG_WEB_MAIN_DOMAIN_NAME }}
      WEB_DOMAIN_NAMES: ${{ vars.STAG_WEB_DOMAIN_NAMES }}
      WEB_SSM_SP_BUCKET_NAME: ${{ vars.STAG_WEB_SSM_SP_BUCKET_NAME }}
      WEB_SSM_SP_DISTRIBUTION_ID: ${{ vars.STAG_WEB_SSM_SP_DISTRIBUTION_ID }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACM_CERTIFICATE_ID: ${{ secrets.AWS_ACM_CERTIFICATE_ID }}
      AWS_OIDC_ASSUME_ROLE: ${{ secrets.AWS_CDK_DEPLOY_OIDC_ASSUME_ROLE }}

  hugo:
    if: ${{ needs.dispatcher.outputs.changes == 'true' }}
    needs: [cdk_tests, cdk_deploy]
    uses: ./.github/workflows/reusable-hugo.yml
    with:
      GHA_ENVIRONMENT: stag-web
      HUGO_ENVIRONMENT: stag
      HUGO_CONFIGS: ${{ vars.STAG_HUGO_CONFIGS }}
      WEB_MAIN_DOMAIN_NAME: ${{ vars.STAG_WEB_MAIN_DOMAIN_NAME }}
      WEB_SSM_SP_BUCKET_NAME: ${{ vars.STAG_WEB_SSM_SP_BUCKET_NAME }}
      WEB_SSM_SP_DISTRIBUTION_ID: ${{ vars.STAG_WEB_SSM_SP_DISTRIBUTION_ID }}
    secrets:
      AWS_OIDC_ASSUME_ROLE: ${{ secrets.AWS_WEB_DEPLOY_OIDC_ASSUME_ROLE }}
